In [1]:
from datascience import *
import numpy as np

'imports complete'

'imports complete'

## Numbers ##

In [ ]:
 ## there are different types of numbers in python
 ## different operations (+, -, /, *, **) default to different types

In [2]:
# int, no decimal
9

9

In [3]:
# int*int => int, no decimal
9*9

81

In [4]:
# int/int  => float, decimal
9/10

0.9

In [5]:
# what about if it is division with no "remainder"
9/9

1.0

In [6]:
# exponentiation
9 ** 2

81

In [14]:
## benefit of integers is that you can store a lot of numbers without limits,
## floats have limits to the number of decimal points (15-16 decimal points)
123456789 ** 2

15241578750190521

In [15]:
123456789 ** 1234

ValueError: Exceeds the limit (4300 digits) for integer string conversion; use sys.set_int_max_str_digits() to increase the limit

In [8]:
 ## floats are only only accurant to a certain number of decimal points
10 / 3

3.3333333333333335

In [16]:
 ## python cuts off some numbers
0.12345678901234567890123456789

0.12345678901234568

In [17]:
##  depending on the level of precision you need, this can be problematic 
0.12345678901234567890123456789 - 0.1234567890123456789

0.0

In [18]:
10 ** 0.5

3.1622776601683795

In [19]:
(10 ** 0.5) ** 2

10.000000000000002

In [20]:
## division results in a float, BUT... 
20 / 10 

2.0

In [21]:
## can convert a float to an int
int(20 / 10) 

2

In [22]:
## will round decimals
int(20 / 9) 

2

In [23]:
float(3)

3.0

In [24]:
6 / 4

1.5

In [25]:
6 / 4000

0.0015

In [26]:
## python knows scientific notation
6 / 400000000000000000000000000000000000000000000000000000000 

1.5e-56

In [27]:
400000000000000000000000000000000000000000000000000000000 * 1.5e-56 

6.0

In [28]:
1.5e-56 

1.5e-56

In [29]:
x = 5

In [30]:
2 * x

10

In [31]:
round(3.7)

4

In [32]:
round(2.00000052345324, ndigits=2)

2.0

In [33]:
10 * 3.0

30.0

In [34]:
## when does this matter?

## Strings ##

In [ ]:
"We made it through week 1 of the term"

In [ ]:
"Let's go!"

In [ ]:
'Let's go!'

In [ ]:
# concatenation  ("glue" the strings together)
'Da' + 'ta' 

In [ ]:
'Sci' + 'ence'

In [ ]:
'Data' + ' ' + 'Science'

In [ ]:
'ha' * 10

In [ ]:
'no' * 3.0

In [ ]:
## maybe your data didn't load correctly, it thinks you numeric data are strings
int('3') 

In [ ]:
int('3.0')

In [ ]:
float('3.0')

In [ ]:
int(float('3.0'))

In [ ]:
float('3.0')

In [ ]:
# can convert any numeric to a string
str(3) 

In [ ]:
str(4.5)

In [ ]:
## when does this matter?

## Types ##

In [ ]:
type(10)

In [ ]:
a = 10
type(a)

In [ ]:
type(4.5)

In [ ]:
type(4 + 4)

In [ ]:
type('abc')

In [ ]:
type(True)

In [ ]:
type(abs)

In [ ]:
## when is it important to know what type your data is?

## Arrays ##

In [35]:
## make an array, must be all the same type of data!
my_array = make_array(1, 2, 3, 4)

In [36]:
my_array

array([1, 2, 3, 4])

In [37]:
## python does operations (+, -, *, /) to every "element" of the array
my_array+1

array([2, 3, 4, 5])

In [38]:
my_array * 0.2

array([ 0.2,  0.4,  0.6,  0.8])

In [39]:
my_array ** 2

array([ 1,  4,  9, 16])

In [ ]:
## did my array change? 
my_array 

In [ ]:
my_array = my_array + 1

In [ ]:
## how many elements in this array?
len(my_array) 

In [ ]:
## what is the sum of the elements? 
sum(my_array) 

In [ ]:
## take the average
sum(my_array) / len(my_array)

In [ ]:
np.average(my_array)
## note the np

In [41]:
another = make_array(60, 70, 80, 90)
another

array([60, 70, 80, 90])

In [ ]:
## Add two arrays, must be same type, same length

In [42]:
my_array + another

array([61, 72, 83, 94])

## What happens if you try to add two arrays of different lengths ?
## How can you find out?

#### a) Try a short experiment!
#### b) Look in the course text
#### c) Check the tip sheet
#### d) Do an internet search

In [ ]:
yet_another = make_array(5, 6, 7)

In [ ]:
my_array + yet_another

In [ ]:
## an array of strings, what's something with a 3-4 catagories? 
colors = make_array("blue", "red", "yellow", "lavender")
colors

In [ ]:
type(colors)

In [ ]:
colors + my_array

In [ ]:
sum(colors)

In [ ]:
len(colors)

In [ ]:
## give me the 1st element
colors.item(0)

In [ ]:
## give me the 3rd element
colors.item(2)

In [ ]:
## why doesn't this give the 3rd element?
colors.item(3)




In [ ]:
## python tricky point, indexing starts at 0